name: Table Parser CI
on:
  push:
  pull_request:
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Ensure gofmt
        run: test -z "$(gofmt -s -d .)"

      - name: Ensure go.mod is already tidied
        run: go mod tidy

      - name: Run unit tests
        run: go test ./...